//
//  CounterPresenterTest.swift
//  JatApp CounterTests
//
//  Created by Mykola Rudenko on 23.01.2021.
//

import XCTest
@testable import JatApp_Counter

class MockCounterView: CounterViewProtocol {
    
    func showText(sandboxText: SandboxText) {
    }
    
    func showLoadError(alert: UIAlertController) {
    }
    
}

class CounterPresenterTest: XCTestCase {
    
    var view: MockCounterView!
    var presenter: CounterViewPresenterProtocol!
    var networkService: NetworkServiceProtocol!
    var router: RouterProtocol!

    override func setUpWithError() throws {
        let nc = UINavigationController()
        let assembly = AssemblyModuleBuilder()
        router = Router(navigationController: nc, assemblyBuilder: assembly)
    }

    override func tearDownWithError() throws {
        view = nil
        networkService = nil
        presenter = nil
    }
    
    func testCharCounter() {

            let view = MockCounterView()
            let networkService = MockNetworkService(text: SandboxText(success: true, data: "hello", errors: nil))
            presenter = CounterPresenter(view: view, networkService: networkService, router: router)
            presenter.countCharacters(inputText: "hello")
        
        // arr = ["h" : 1, "e" : 1, "l" : 2, "o" : 1]
        XCTAssertFalse(presenter.countsArr.isEmpty)
        XCTAssertTrue(presenter.countsArr[0].key == "l")
        XCTAssertTrue(presenter.countsArr[0].value == 2)
    }

    func testCountingPerformance() throws {
        
        let testText =
            """
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Maecenas sed enim ut sem viverra. Leo vel orci porta non pulvinar neque laoreet. Fermentum iaculis eu non diam. Mattis vulputate enim nulla aliquet porttitor lacus luctus. Dui id ornare arcu odio. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Aliquet risus feugiat in ante metus dictum at. Pellentesque diam volutpat commodo sed. Nec ullamcorper sit amet risus nullam eget felis eget. Est pellentesque elit ullamcorper dignissim. Mauris in aliquam sem fringilla ut morbi tincidunt augue interdum. Semper risus in hendrerit gravida rutrum quisque non tellus orci. Erat pellentesque adipiscing commodo elit at. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan.

        Risus nec feugiat in fermentum posuere. Risus nec feugiat in fermentum posuere. Curabitur gravida arcu ac tortor. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Arcu bibendum at varius vel pharetra vel turpis. Nisi vitae suscipit tellus mauris a. Laoreet suspendisse interdum consectetur libero. Quisque sagittis purus sit amet volutpat consequat mauris nunc. Tortor condimentum lacinia quis vel. Mi quis hendrerit dolor magna eget est. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo.

        Ultrices dui sapien eget mi proin. Tellus elementum sagittis vitae et. Dui faucibus in ornare quam viverra orci sagittis. Nulla posuere sollicitudin aliquam ultrices sagittis orci. At imperdiet dui accumsan sit amet nulla facilisi morbi. A diam sollicitudin tempor id eu nisl. Montes nascetur ridiculus mus mauris. Quam id leo in vitae turpis massa sed. Sit amet nulla facilisi morbi tempus iaculis urna id. Diam ut venenatis tellus in metus vulputate eu.

        Ultrices vitae auctor eu augue ut lectus arcu bibendum. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. In massa tempor nec feugiat nisl pretium. Ut consequat semper viverra nam libero justo laoreet sit amet. In eu mi bibendum neque egestas congue. Pellentesque elit eget gravida cum sociis natoque penatibus. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Sed euismod nisi porta lorem mollis aliquam ut. Blandit massa enim nec dui nunc mattis. Ornare aenean euismod elementum nisi quis eleifend. Cras adipiscing enim eu turpis egestas. Eget aliquet nibh praesent tristique. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo. Senectus et netus et malesuada fames ac. Lorem donec massa sapien faucibus et molestie ac feugiat sed.

        Facilisi nullam vehicula ipsum a. Netus et malesuada fames ac turpis egestas. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Mauris cursus mattis molestie a iaculis at erat pellentesque. Sit amet mauris commodo quis. Bibendum est ultricies integer quis auctor elit. Est velit egestas dui id ornare. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Eu lobortis elementum nibh tellus molestie nunc non blandit. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eu non diam phasellus vestibulum lorem sed. Nullam non nisi est sit amet facilisis magna etiam. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Aliquam nulla facilisi cras fermentum odio eu feugiat. Eu mi bibendum neque egestas congue quisque egestas. Fames ac turpis egestas sed tempus urna et.

        Nam libero justo laoreet sit amet cursus sit. Cursus risus at ultrices mi tempus imperdiet. Vestibulum morbi blandit cursus risus at ultrices mi. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Velit egestas dui id ornare arcu odio ut sem. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Curabitur gravida arcu ac tortor. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus.

        Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Volutpat est velit egestas dui. Est placerat in egestas erat imperdiet sed euismod nisi. Congue nisi vitae suscipit tellus. Est lorem ipsum dolor sit amet consectetur adipiscing elit. Est velit egestas dui id ornare arcu odio ut sem. Risus nec feugiat in fermentum posuere urna. Vel risus commodo viverra maecenas accumsan lacus vel. Vestibulum lorem sed risus ultricies tristique. Sodales ut eu sem integer vitae justo. Porta nibh venenatis cras sed felis. Gravida rutrum quisque non tellus orci ac auctor augue.

        Diam vel quam elementum pulvinar etiam non quam. Donec ac odio tempor orci. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Molestie ac feugiat sed lectus. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. In eu mi bibendum neque egestas congue quisque. Sed arcu non odio euismod lacinia. Dolor sed viverra ipsum nunc aliquet. Nam libero justo laoreet sit amet cursus. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Velit ut tortor pretium viverra suspendisse potenti nullam. Nibh ipsum consequat nisl vel pretium lectus. Ultricies integer quis auctor elit sed vulputate mi sit.

        Et leo duis ut diam quam nulla porttitor massa. Iaculis urna id volutpat lacus. Gravida cum sociis natoque penatibus et magnis. Neque ornare aenean euismod elementum. Egestas erat imperdiet sed euismod nisi. Semper quis lectus nulla at. Eu consequat ac felis donec et odio pellentesque. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Ut eu sem integer vitae. Faucibus et molestie ac feugiat. Lectus urna duis convallis convallis tellus id interdum velit laoreet. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Orci ac auctor augue mauris augue neque. Rutrum quisque non tellus orci ac auctor. At tellus at urna condimentum mattis. Tellus mauris a diam maecenas sed. Adipiscing at in tellus integer feugiat scelerisque varius morbi enim. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit.

        Sit amet commodo nulla facilisi nullam vehicula ipsum. Morbi leo urna molestie at elementum eu facilisis sed. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Diam vel quam elementum pulvinar etiam. Elit sed vulputate mi sit amet mauris commodo quis. Tortor id aliquet lectus proin nibh nisl condimentum. Neque egestas congue quisque egestas diam in. Nibh tortor id aliquet lectus proin nibh nisl condimentum. Amet est placerat in egestas erat imperdiet sed euismod nisi. Cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Aenean pharetra magna ac placerat vestibulum lectus.

        Arcu ac tortor dignissim convallis aenean et tortor at risus. Lectus urna duis convallis convallis. Arcu non odio euismod lacinia at quis risus sed. Pellentesque id nibh tortor id aliquet lectus. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Nunc pulvinar sapien et ligula. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Sed odio morbi quis commodo odio aenean. Quis hendrerit dolor magna eget est lorem ipsum. Neque gravida in fermentum et sollicitudin ac orci phasellus. Odio ut enim blandit volutpat maecenas volutpat. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Semper eget duis at tellus at. Ut sem viverra aliquet eget sit amet tellus. Massa tincidunt dui ut ornare lectus sit amet. Vel fringilla est ullamcorper eget. Rhoncus est pellentesque elit ullamcorper dignissim.

        Dui sapien eget mi proin sed libero enim sed faucibus. Suspendisse potenti nullam ac tortor vitae purus. Varius vel pharetra vel turpis nunc eget lorem dolor. Ut venenatis tellus in metus vulputate eu scelerisque felis. Ut enim blandit volutpat maecenas. Risus ultricies tristique nulla aliquet enim. Enim facilisis gravida neque convallis. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Fermentum iaculis eu non diam phasellus vestibulum. Tristique nulla aliquet enim tortor at auctor. Ornare arcu odio ut sem nulla pharetra diam. Ultricies integer quis auctor elit sed vulputate mi. Eget nulla facilisi etiam dignissim diam quis enim. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Pellentesque sit amet porttitor eget. Diam maecenas sed enim ut sem viverra aliquet. Lectus magna fringilla urna porttitor rhoncus dolor purus non. Libero id faucibus nisl tincidunt eget nullam non nisi est. Leo vel orci porta non pulvinar. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant.

        Sit amet purus gravida quis. Odio ut sem nulla pharetra diam sit. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Blandit volutpat maecenas volutpat blandit aliquam etiam. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Dui faucibus in ornare quam viverra orci sagittis eu. Proin nibh nisl condimentum id venenatis a condimentum. Eu tincidunt tortor aliquam nulla. Pretium fusce id velit ut tortor pretium viverra. Lectus magna fringilla urna porttitor rhoncus. Integer feugiat scelerisque varius morbi enim nunc. Pulvinar neque laoreet suspendisse interdum consectetur libero id. Iaculis at erat pellentesque adipiscing commodo elit. Malesuada nunc vel risus commodo viverra maecenas accumsan. In cursus turpis massa tincidunt dui ut. Etiam erat velit scelerisque in dictum non consectetur a. Aliquam nulla facilisi cras fermentum odio. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Fames ac turpis egestas maecenas pharetra.

        Ultricies integer quis auctor elit sed vulputate mi. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Sit amet consectetur adipiscing elit. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Enim praesent elementum facilisis leo vel fringilla est. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Ultrices sagittis orci a scelerisque. Et molestie ac feugiat sed lectus vestibulum mattis. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Nisl condimentum id venenatis a condimentum vitae.

        Tellus in hac habitasse platea dictumst vestibulum. Diam ut venenatis tellus in metus vulputate. Ornare suspendisse sed nisi lacus sed viverra tellus in. Nec ultrices dui sapien eget mi. Massa tincidunt dui ut ornare lectus. Dictum non consectetur a erat nam at lectus. Massa tincidunt nunc pulvinar sapien et. Suscipit adipiscing bibendum est ultricies integer quis auctor. Id velit ut tortor pretium viverra suspendisse potenti. Dui accumsan sit amet nulla facilisi. Pharetra massa massa ultricies mi quis. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Tortor consequat id porta nibh venenatis. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Aliquet bibendum enim facilisis gravida neque convallis. Dictumst quisque sagittis purus sit amet. Sit amet cursus sit amet dictum sit.

        Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Cras fermentum odio eu feugiat pretium. Tincidunt tortor aliquam nulla facilisi. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Molestie at elementum eu facilisis sed. Massa tempor nec feugiat nisl pretium fusce id. Massa eget egestas purus viverra accumsan in. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Metus aliquam eleifend mi in. Consequat ac felis donec et odio. Fermentum leo vel orci porta. Odio pellentesque diam volutpat commodo sed egestas egestas. Egestas erat imperdiet sed euismod nisi porta lorem. In nibh mauris cursus mattis molestie a iaculis. Dis parturient montes nascetur ridiculus mus mauris vitae. Mollis aliquam ut porttitor leo a diam sollicitudin tempor. Neque volutpat ac tincidunt vitae semper quis lectus nulla at. Sem fringilla ut morbi tincidunt augue interdum. Velit aliquet sagittis id consectetur purus ut faucibus. Nunc vel risus commodo viverra maecenas accumsan lacus vel facilisis.

        Elementum sagittis vitae et leo duis ut diam quam nulla. Scelerisque varius morbi enim nunc. Egestas integer eget aliquet nibh praesent tristique. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Accumsan tortor posuere ac ut consequat. Et malesuada fames ac turpis egestas sed tempus. Quis varius quam quisque id diam vel quam elementum. Vestibulum rhoncus est pellentesque elit. Viverra suspendisse potenti nullam ac tortor vitae purus. Aliquam sem fringilla ut morbi tincidunt. Lectus mauris ultrices eros in cursus turpis. Eu consequat ac felis donec. Et magnis dis parturient montes nascetur ridiculus. Fringilla phasellus faucibus scelerisque eleifend donec. Bibendum at varius vel pharetra vel.

        Leo in vitae turpis massa sed elementum tempus. Enim facilisis gravida neque convallis a cras semper. Adipiscing enim eu turpis egestas. Sed id semper risus in hendrerit. Vestibulum lectus mauris ultrices eros in cursus. Urna nunc id cursus metus aliquam eleifend mi in. Risus in hendrerit gravida rutrum quisque non tellus. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis a. Mus mauris vitae ultricies leo integer malesuada. Ut diam quam nulla porttitor massa id neque. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et.

        Egestas sed tempus urna et. At augue eget arcu dictum varius duis. Imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor. Ipsum nunc aliquet bibendum enim facilisis. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Sit amet consectetur adipiscing elit duis tristique. In est ante in nibh mauris. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Non blandit massa enim nec dui nunc mattis enim. Porta non pulvinar neque laoreet suspendisse interdum. Dictumst quisque sagittis purus sit amet volutpat consequat. Ac orci phasellus egestas tellus. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Mattis molestie a iaculis at erat. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Augue neque gravida in fermentum et. Ac turpis egestas integer eget aliquet nibh praesent tristique. Enim nulla aliquet porttitor lacus luctus. Tempor nec feugiat nisl pretium fusce id velit ut tortor.

        Nascetur ridiculus mus mauris vitae ultricies leo integer. In mollis nunc sed id. Id donec ultrices tincidunt arcu non sodales neque. Urna cursus eget nunc scelerisque viverra. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Feugiat vivamus at augue eget arcu. Mattis aliquam faucibus purus in massa tempor nec. Euismod lacinia at quis risus sed. Mi quis hendrerit dolor magna eget. Quis blandit turpis cursus in hac habitasse. Sit amet facilisis magna etiam tempor orci. Porta lorem mollis aliquam ut porttitor leo. Mauris sit amet massa vitae tortor condimentum lacinia. Non blandit massa enim nec. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Id venenatis a condimentum vitae sapien pellentesque. Tempus imperdiet nulla malesuada pellentesque elit. At risus viverra adipiscing at in tellus integer feugiat scelerisque. Felis eget nunc lobortis mattis aliquam faucibus purus. Lectus mauris ultrices eros in cursus turpis massa tincidunt dui.

        Euismod elementum nisi quis eleifend quam adipiscing vitae. In nibh mauris cursus mattis molestie a iaculis. Sed enim ut sem viverra aliquet eget sit amet. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Aliquam etiam erat velit scelerisque in dictum. Nibh tellus molestie nunc non blandit massa enim nec. Habitasse platea dictumst quisque sagittis. Leo duis ut diam quam nulla porttitor. Tellus in hac habitasse platea dictumst. Proin nibh nisl condimentum id venenatis. Tortor at auctor urna nunc id cursus metus aliquam. Dignissim diam quis enim lobortis scelerisque. Non blandit massa enim nec. Ut ornare lectus sit amet est placerat in. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Quis blandit turpis cursus in hac habitasse. Ut venenatis tellus in metus vulputate eu scelerisque. Suspendisse sed nisi lacus sed viverra tellus in. Habitant morbi tristique senectus et netus et malesuada.

        Odio ut sem nulla pharetra diam sit. Enim praesent elementum facilisis leo vel fringilla est ullamcorper. Cras tincidunt lobortis feugiat vivamus at. In hendrerit gravida rutrum quisque. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Turpis massa sed elementum tempus egestas sed sed risus. Viverra nibh cras pulvinar mattis nunc sed. Euismod lacinia at quis risus sed vulputate odio ut enim. Quis auctor elit sed vulputate mi sit. Sed libero enim sed faucibus turpis in eu. Aliquam faucibus purus in massa tempor. Lacus laoreet non curabitur gravida. Massa sapien faucibus et molestie ac feugiat. At auctor urna nunc id cursus metus. Amet est placerat in egestas erat imperdiet sed euismod. Pulvinar elementum integer enim neque volutpat. Fermentum posuere urna nec tincidunt. Mauris augue neque gravida in fermentum. Sed viverra tellus in hac. Auctor augue mauris augue neque.

        Lobortis mattis aliquam faucibus purus in massa tempor. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Dignissim convallis aenean et tortor at. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Amet tellus cras adipiscing enim eu. Velit laoreet id donec ultrices tincidunt. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Platea dictumst vestibulum rhoncus est pellentesque elit. Leo urna molestie at elementum eu facilisis sed. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Iaculis eu non diam phasellus vestibulum lorem sed. Viverra adipiscing at in tellus integer feugiat. Nulla porttitor massa id neque aliquam vestibulum morbi blandit. Morbi tincidunt ornare massa eget egestas purus viverra.

        Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Dui ut ornare lectus sit amet est. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Vitae proin sagittis nisl rhoncus mattis. Risus sed vulputate odio ut enim. Suscipit adipiscing bibendum est ultricies integer. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Et netus et malesuada fames ac turpis egestas maecenas. Commodo ullamcorper a lacus vestibulum sed. Duis convallis convallis tellus id interdum velit laoreet. In nisl nisi scelerisque eu ultrices vitae auctor. At urna condimentum mattis pellentesque id nibh tortor id. Morbi blandit cursus risus at ultrices mi tempus. Purus semper eget duis at tellus at urna. Viverra nam libero justo laoreet.

        Posuere urna nec tincidunt praesent semper feugiat nibh. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Quisque sagittis purus sit amet volutpat consequat mauris. Bibendum at varius vel pharetra. Magna sit amet purus gravida quis blandit turpis. Eu consequat ac felis donec et odio pellentesque diam. Egestas sed tempus urna et pharetra pharetra massa. Viverra justo nec ultrices dui sapien eget mi. Pellentesque habitant morbi tristique senectus et. At tempor commodo ullamcorper a. Enim sed faucibus turpis in eu mi bibendum. Pretium nibh ipsum consequat nisl vel pretium lectus quam id. Risus feugiat in ante metus dictum at tempor commodo. Justo laoreet sit amet cursus sit amet dictum sit amet. Vitae proin sagittis nisl rhoncus. Et leo duis ut diam quam nulla. Eros donec ac odio tempor orci dapibus ultrices in. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse.

        Nulla aliquet porttitor lacus luctus. Vulputate ut pharetra sit amet aliquam. At auctor urna nunc id. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Sit amet volutpat consequat mauris nunc congue nisi. Viverra aliquet eget sit amet. Dignissim diam quis enim lobortis scelerisque fermentum dui. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Nisl tincidunt eget nullam non nisi est sit amet facilisis. Tellus id interdum velit laoreet. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Condimentum lacinia quis vel eros donec ac odio tempor orci. Ut venenatis tellus in metus vulputate eu scelerisque. Dolor sit amet consectetur adipiscing. Nibh venenatis cras sed felis.

        Nec ultrices dui sapien eget mi. Iaculis eu non diam phasellus. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Interdum varius sit amet mattis vulputate enim nulla aliquet. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Proin fermentum leo vel orci porta non pulvinar neque. Fermentum posuere urna nec tincidunt. Neque ornare aenean euismod elementum nisi quis eleifend. Amet aliquam id diam maecenas. Pellentesque dignissim enim sit amet venenatis. Erat velit scelerisque in dictum. Pellentesque adipiscing commodo elit at imperdiet. Id eu nisl nunc mi ipsum faucibus vitae aliquet nec.

        Felis eget velit aliquet sagittis id consectetur purus. Consequat nisl vel pretium lectus quam id leo in vitae. Senectus et netus et malesuada fames ac. Pulvinar etiam non quam lacus. Sodales ut eu sem integer vitae. Sit amet mattis vulputate enim nulla aliquet. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. In hac habitasse platea dictumst quisque. Eget aliquet nibh praesent tristique magna sit. Sed adipiscing diam donec adipiscing tristique. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Vitae purus faucibus ornare suspendisse. Sed enim ut sem viverra aliquet eget sit amet tellus. Arcu dui vivamus arcu felis bibendum ut. Aliquam purus sit amet luctus venenatis lectus magna fringilla urna.

        Cursus in hac habitasse platea dictumst quisque sagittis purus. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Enim sit amet venenatis urna cursus. Facilisi nullam vehicula ipsum a arcu cursus vitae. Vel pretium lectus quam id leo in. Pellentesque habitant morbi tristique senectus et netus et malesuada. Justo nec ultrices dui sapien. Ac tincidunt vitae semper quis lectus nulla at volutpat diam. Ut tellus elementum sagittis vitae et leo. Integer quis auctor elit sed vulputate mi sit amet mauris. Maecenas ultricies mi eget mauris.

        Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Malesuada proin libero nunc consequat interdum varius. Mauris a diam maecenas sed enim ut sem viverra aliquet. Sit amet volutpat consequat mauris nunc. Arcu ac tortor dignissim convallis aenean et tortor at. Quam quisque id diam vel quam elementum. Id interdum velit laoreet id donec ultrices tincidunt. Nunc aliquet bibendum enim facilisis gravida neque convallis. Nascetur ridiculus mus mauris vitae ultricies leo integer. Accumsan lacus vel facilisis volutpat est velit. Scelerisque viverra mauris in aliquam sem fringilla ut morbi. Montes nascetur ridiculus mus mauris vitae ultricies leo. Nunc sed id semper risus in hendrerit gravida rutrum quisque.

        Tortor consequat id porta nibh. Integer eget aliquet nibh praesent. Gravida cum sociis natoque penatibus et magnis dis parturient. Diam maecenas sed enim ut sem. Amet venenatis urna cursus eget. At elementum eu facilisis sed odio morbi. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Maecenas sed enim ut sem. Elit scelerisque mauris pellentesque pulvinar pellentesque. Posuere morbi leo urna molestie at elementum eu. Varius vel pharetra vel turpis nunc eget lorem. Ut aliquam purus sit amet luctus venenatis. Aliquam sem fringilla ut morbi tincidunt augue. In cursus turpis massa tincidunt.

        Urna et pharetra pharetra massa massa ultricies. Nibh mauris cursus mattis molestie a iaculis at. Viverra adipiscing at in tellus integer feugiat scelerisque varius morbi. Risus ultricies tristique nulla aliquet enim. Aliquam sem et tortor consequat. Pharetra convallis posuere morbi leo urna molestie. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. At elementum eu facilisis sed odio morbi. Quisque id diam vel quam. Integer eget aliquet nibh praesent tristique magna.

        Integer malesuada nunc vel risus commodo. Porttitor eget dolor morbi non arcu risus quis. Volutpat ac tincidunt vitae semper. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Nullam non nisi est sit amet facilisis magna etiam. Dolor sed viverra ipsum nunc aliquet bibendum. Egestas integer eget aliquet nibh praesent tristique magna sit amet. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Faucibus pulvinar elementum integer enim neque volutpat ac. Eget est lorem ipsum dolor sit amet. Nunc mattis enim ut tellus elementum sagittis vitae et. Enim nunc faucibus a pellentesque sit amet. Nullam non nisi est sit. Mi sit amet mauris commodo quis imperdiet massa. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Aliquet risus feugiat in ante. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Leo integer malesuada nunc vel risus commodo viverra.

        Justo nec ultrices dui sapien eget mi proin. Id consectetur purus ut faucibus. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Volutpat est velit egestas dui id ornare arcu odio. Amet commodo nulla facilisi nullam vehicula. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Blandit turpis cursus in hac habitasse platea dictumst quisque sagittis. Proin libero nunc consequat interdum varius sit amet mattis vulputate. In arcu cursus euismod quis viverra nibh cras pulvinar. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Iaculis at erat pellentesque adipiscing commodo. Consectetur libero id faucibus nisl tincidunt. Varius vel pharetra vel turpis nunc eget lorem. Quam id leo in vitae. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.

        Id faucibus nisl tincidunt eget nullam non nisi. Hendrerit gravida rutrum quisque non tellus orci ac auctor augue. In cursus turpis massa tincidunt dui. Scelerisque purus semper eget duis at tellus at. Vitae turpis massa sed elementum tempus. Massa ultricies mi quis hendrerit dolor. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Sit amet facilisis magna etiam. Feugiat nisl pretium fusce id velit. Feugiat nisl pretium fusce id velit ut tortor. Risus sed vulputate odio ut enim blandit volutpat.

        Orci ac auctor augue mauris. Tristique senectus et netus et. Lorem donec massa sapien faucibus et molestie ac. Nam libero justo laoreet sit. Praesent elementum facilisis leo vel fringilla. Et netus et malesuada fames. Libero id faucibus nisl tincidunt eget nullam. Bibendum ut tristique et egestas. In hendrerit gravida rutrum quisque non. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Vivamus arcu felis bibendum ut tristique et. Massa placerat duis ultricies lacus sed turpis tincidunt id. Dolor purus non enim praesent elementum facilisis leo vel.

        Id venenatis a condimentum vitae sapien. Integer enim neque volutpat ac tincidunt. Porttitor massa id neque aliquam vestibulum morbi. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Rutrum quisque non tellus orci ac auctor. Diam vel quam elementum pulvinar. Aliquam faucibus purus in massa tempor nec feugiat nisl. Varius duis at consectetur lorem. Nam aliquam sem et tortor. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Volutpat blandit aliquam etiam erat velit scelerisque. Tortor at risus viverra adipiscing at. Morbi quis commodo odio aenean. Sit amet consectetur adipiscing elit ut. Id semper risus in hendrerit gravida rutrum quisque non. Risus pretium quam vulputate dignissim suspendisse in est ante. Pretium vulputate sapien nec sagittis.

        Donec adipiscing tristique risus nec feugiat in fermentum. Fames ac turpis egestas maecenas pharetra. Nam libero justo laoreet sit amet cursus sit. Sit amet justo donec enim. Auctor augue mauris augue neque. Arcu odio ut sem nulla pharetra diam sit amet. Nec dui nunc mattis enim ut tellus. Orci nulla pellentesque dignissim enim sit. Sed felis eget velit aliquet. Lacinia at quis risus sed. Vel turpis nunc eget lorem dolor sed viverra. Sed elementum tempus egestas sed sed risus. Ultricies tristique nulla aliquet enim. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Nibh tellus molestie nunc non blandit massa enim. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Elementum facilisis leo vel fringilla est. Vitae justo eget magna fermentum iaculis eu.

        Sagittis id consectetur purus ut faucibus. Varius quam quisque id diam vel quam elementum pulvinar. Mattis nunc sed blandit libero volutpat sed cras ornare arcu. At imperdiet dui accumsan sit amet. Sit amet nisl purus in mollis. Faucibus vitae aliquet nec ullamcorper sit amet risus. Nibh sit amet commodo nulla facilisi. In hendrerit gravida rutrum quisque non tellus. Urna neque viverra justo nec ultrices. Maecenas volutpat blandit aliquam etiam. Egestas integer eget aliquet nibh praesent tristique magna sit. Erat pellentesque adipiscing commodo elit.

        Ipsum a arcu cursus vitae. Scelerisque felis imperdiet proin fermentum leo. Praesent tristique magna sit amet purus gravida. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Sed enim ut sem viverra aliquet eget sit. Urna id volutpat lacus laoreet non curabitur. A pellentesque sit amet porttitor eget dolor morbi. In hac habitasse platea dictumst quisque sagittis purus sit. Interdum varius sit amet mattis vulputate enim. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. Massa vitae tortor condimentum lacinia quis. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Cras ornare arcu dui vivamus arcu. Netus et malesuada fames ac turpis. Habitant morbi tristique senectus et netus et malesuada fames. Orci porta non pulvinar neque laoreet suspendisse.

        Ut tellus elementum sagittis vitae et leo duis ut. Ornare arcu dui vivamus arcu felis bibendum ut tristique. Nunc scelerisque viverra mauris in aliquam sem fringilla ut morbi. Ultrices sagittis orci a scelerisque purus semper eget duis at. In mollis nunc sed id. Nisl purus in mollis nunc. Sit amet volutpat consequat mauris nunc congue. Convallis aenean et tortor at risus viverra adipiscing. Pretium fusce id velit ut tortor. Molestie nunc non blandit massa enim nec dui nunc mattis. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Viverra mauris in aliquam sem fringilla.

        Consectetur lorem donec massa sapien faucibus et. Commodo elit at imperdiet dui accumsan sit. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus iaculis. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Malesuada fames ac turpis egestas integer. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Arcu cursus euismod quis viverra. Feugiat vivamus at augue eget arcu dictum varius duis. Placerat in egestas erat imperdiet sed. Donec et odio pellentesque diam volutpat commodo sed. Odio aenean sed adipiscing diam donec adipiscing. Ac feugiat sed lectus vestibulum mattis. Scelerisque mauris pellentesque pulvinar pellentesque.

        Facilisi etiam dignissim diam quis enim. Ornare lectus sit amet est placerat in egestas erat imperdiet. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Odio facilisis mauris sit amet massa. Lacinia quis vel eros donec ac odio tempor orci dapibus. Adipiscing elit ut aliquam purus sit amet luctus. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Non consectetur a erat nam at lectus urna. Justo eget magna fermentum iaculis. Iaculis nunc sed augue lacus viverra vitae congue eu. Blandit libero volutpat sed cras ornare arcu. Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Arcu non odio euismod lacinia. Mauris nunc congue nisi vitae suscipit tellus mauris. Nullam vehicula ipsum a arcu cursus vitae congue. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Morbi leo urna molestie at. Pellentesque id nibh tortor id aliquet lectus proin. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim.

        Orci ac auctor augue mauris. Malesuada proin libero nunc consequat interdum varius. Eleifend quam adipiscing vitae proin. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Massa eget egestas purus viverra. Turpis in eu mi bibendum neque egestas congue. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Amet aliquam id diam maecenas ultricies. Id consectetur purus ut faucibus. Vitae ultricies leo integer malesuada nunc. Morbi tristique senectus et netus.

        Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Fames ac turpis egestas integer eget aliquet nibh praesent tristique. Pulvinar mattis nunc sed blandit libero. Vel orci porta non pulvinar neque laoreet suspendisse interdum. Quis enim lobortis scelerisque fermentum. Elementum sagittis vitae et leo duis ut diam. Senectus et netus et malesuada fames. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Aliquam sem et tortor consequat. Mi sit amet mauris commodo quis imperdiet. Diam vulputate ut pharetra sit amet aliquam id. Ipsum nunc aliquet bibendum enim. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Mauris cursus mattis molestie a iaculis at. A erat nam at lectus. Elit ut aliquam purus sit. Integer quis auctor elit sed vulputate.

        Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Pretium lectus quam id leo in vitae turpis. Amet tellus cras adipiscing enim eu turpis egestas. Suspendisse interdum consectetur libero id. Purus in massa tempor nec feugiat. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Blandit aliquam etiam erat velit scelerisque in dictum. Nunc eget lorem dolor sed viverra ipsum. Morbi tristique senectus et netus et malesuada. Nulla at volutpat diam ut. Vitae aliquet nec ullamcorper sit amet. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Lobortis feugiat vivamus at augue eget arcu dictum varius. Vel quam elementum pulvinar etiam non. Fusce ut placerat orci nulla pellentesque dignissim.

        Accumsan sit amet nulla facilisi. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Rutrum quisque non tellus orci ac auctor augue mauris augue. Convallis aenean et tortor at risus viverra. Curabitur vitae nunc sed velit dignissim sodales. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Scelerisque felis imperdiet proin fermentum leo. Fringilla ut morbi tincidunt augue. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Nam libero justo laoreet sit amet cursus. Sed turpis tincidunt id aliquet risus feugiat. Curabitur gravida arcu ac tortor dignissim convallis aenean. In arcu cursus euismod quis viverra nibh cras. Pretium vulputate sapien nec sagittis aliquam.

        Urna nec tincidunt praesent semper. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Nam libero justo laoreet sit amet cursus sit. Amet est placerat in egestas erat imperdiet sed euismod nisi. Non tellus orci ac auctor augue mauris augue neque. Tortor at risus viverra adipiscing at in tellus. Facilisis sed odio morbi quis commodo odio aenean. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Posuere ac ut consequat semper viverra nam libero. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Urna nunc id cursus metus aliquam eleifend mi in. Mollis nunc sed id semper risus in hendrerit. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. At erat pellentesque adipiscing commodo. Ipsum dolor sit amet consectetur.

        Et malesuada fames ac turpis. Integer quis auctor elit sed vulputate mi sit amet mauris. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Ac placerat vestibulum lectus mauris ultrices eros in. Etiam sit amet nisl purus in mollis nunc sed id. Pellentesque diam volutpat commodo sed egestas. Fusce ut placerat orci nulla pellentesque dignissim enim. Eget mi proin sed libero enim sed faucibus turpis in. Aliquam etiam erat velit scelerisque in. Aliquet nec ullamcorper sit amet risus. Malesuada fames ac turpis egestas integer eget aliquet. Eleifend quam adipiscing vitae proin sagittis nisl. Egestas diam in arcu cursus euismod quis viverra nibh cras.

        Risus feugiat in ante metus dictum at. Nibh sed pulvinar proin gravida hendrerit lectus. Amet massa vitae tortor condimentum lacinia quis vel eros donec. Sagittis vitae et leo duis. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Scelerisque felis imperdiet proin fermentum. Feugiat in fermentum posuere urna nec tincidunt. Porta non pulvinar neque laoreet. Parturient montes nascetur ridiculus mus mauris. Risus viverra adipiscing at in tellus integer feugiat. Suspendisse potenti nullam ac tortor vitae purus. Velit sed ullamcorper morbi tincidunt ornare massa. Sit amet est placerat in egestas erat. Risus ultricies tristique nulla aliquet enim tortor at auctor. Laoreet non curabitur gravida arcu ac tortor. Dictum at tempor commodo ullamcorper a lacus vestibulum. Ultrices vitae auctor eu augue ut. Nibh tortor id aliquet lectus. Semper eget duis at tellus at.

        Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Aliquet enim tortor at auctor urna nunc id cursus metus. Morbi tristique senectus et netus et malesuada fames ac. Vitae sapien pellentesque habitant morbi tristique senectus et netus. Sit amet mattis vulputate enim nulla aliquet porttitor. Tristique magna sit amet purus gravida quis blandit turpis cursus. Nulla porttitor massa id neque. Ac odio tempor orci dapibus ultrices in. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Elementum eu facilisis sed odio morbi quis commodo. Tellus pellentesque eu tincidunt tortor aliquam. Ut tortor pretium viverra suspendisse potenti nullam. Nec dui nunc mattis enim ut tellus elementum.

        Pretium fusce id velit ut tortor pretium viverra. Euismod lacinia at quis risus sed vulputate. Parturient montes nascetur ridiculus mus mauris vitae. Nunc faucibus a pellentesque sit amet porttitor. Imperdiet nulla malesuada pellentesque elit eget gravida. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Morbi tincidunt augue interdum velit euismod in. Pharetra et ultrices neque ornare. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Sagittis nisl rhoncus mattis rhoncus urna neque. Lobortis mattis aliquam faucibus purus in massa tempor nec. Non odio euismod lacinia at quis risus sed vulputate. Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Enim diam vulputate ut pharetra sit amet aliquam id. Consequat id porta nibh venenatis cras sed felis. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor.

        Nisl pretium fusce id velit ut tortor pretium. Sed ullamcorper morbi tincidunt ornare massa. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Elementum facilisis leo vel fringilla. Nunc non blandit massa enim nec dui. Nibh tellus molestie nunc non blandit. A lacus vestibulum sed arcu. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Magna ac placerat vestibulum lectus mauris ultrices. Eget magna fermentum iaculis eu.

        Molestie at elementum eu facilisis sed. Purus semper eget duis at. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Dui vivamus arcu felis bibendum ut tristique et egestas. Mauris cursus mattis molestie a iaculis at erat pellentesque. Sem fringilla ut morbi tincidunt augue interdum velit euismod in. Maecenas ultricies mi eget mauris pharetra et ultrices neque ornare. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Dolor magna eget est lorem ipsum dolor sit amet. Tellus molestie nunc non blandit massa enim. Id volutpat lacus laoreet non curabitur gravida. Vulputate mi sit amet mauris commodo quis imperdiet massa.

        Sagittis eu volutpat odio facilisis mauris. Semper risus in hendrerit gravida rutrum quisque. Placerat orci nulla pellentesque dignissim. In hac habitasse platea dictumst vestibulum. Ullamcorper malesuada proin libero nunc consequat. Accumsan lacus vel facilisis volutpat est. Sit amet justo donec enim diam vulputate ut pharetra. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Lectus nulla at volutpat diam ut venenatis tellus. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Bibendum enim facilisis gravida neque convallis a cras semper. Non curabitur gravida arcu ac tortor. Fames ac turpis egestas sed tempus urna et. At volutpat diam ut venenatis tellus. Neque egestas congue quisque egestas diam in. Magna fringilla urna porttitor rhoncus dolor purus non. Donec massa sapien faucibus et molestie ac. Dui ut ornare lectus sit amet est placerat in egestas.

        A pellentesque sit amet porttitor eget dolor morbi non. Viverra justo nec ultrices dui sapien eget mi proin. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Magna fringilla urna porttitor rhoncus dolor purus. Magna etiam tempor orci eu lobortis elementum. Eu non diam phasellus vestibulum. Sit amet dictum sit amet justo donec enim. Placerat vestibulum lectus mauris ultrices. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tempor nec feugiat nisl pretium fusce. Fermentum leo vel orci porta. Cum sociis natoque penatibus et. Vitae nunc sed velit dignissim sodales ut eu sem. Platea dictumst vestibulum rhoncus est pellentesque elit. Purus gravida quis blandit turpis cursus in hac habitasse.

        Eget mauris pharetra et ultrices neque ornare. Neque laoreet suspendisse interdum consectetur libero id faucibus. Semper auctor neque vitae tempus quam pellentesque nec nam. Elementum facilisis leo vel fringilla est. Arcu odio ut sem nulla pharetra diam sit. Dictum non consectetur a erat nam at lectus. Eget arcu dictum varius duis. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Cras sed felis eget velit. Massa eget egestas purus viverra accumsan in. Adipiscing vitae proin sagittis nisl rhoncus. Pharetra diam sit amet nisl suscipit adipiscing bibendum. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Varius vel pharetra vel turpis nunc eget lorem. Aliquam nulla facilisi cras fermentum odio eu. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Ut faucibus pulvinar elementum integer enim neque volutpat.

        Vitae ultricies leo integer malesuada nunc vel risus commodo. Neque laoreet suspendisse interdum consectetur libero id faucibus. Et malesuada fames ac turpis egestas. In dictum non consectetur a erat nam at. Risus sed vulputate odio ut enim blandit volutpat. Duis at consectetur lorem donec massa. Varius vel pharetra vel turpis nunc eget lorem dolor. Congue eu consequat ac felis donec et odio pellentesque. Hendrerit dolor magna eget est lorem. Nulla porttitor massa id neque aliquam. Eu feugiat pretium nibh ipsum consequat. Orci porta non pulvinar neque. Montes nascetur ridiculus mus mauris. Dignissim convallis aenean et tortor at. Tellus id interdum velit laoreet id.

        Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Dolor morbi non arcu risus. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Vitae congue eu consequat ac felis donec et odio. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Velit sed ullamcorper morbi tincidunt ornare massa eget. Ultricies leo integer malesuada nunc vel risus commodo. Euismod lacinia at quis risus sed vulputate odio ut. Pharetra massa massa ultricies mi quis hendrerit dolor magna. A cras semper auctor neque vitae tempus. Pulvinar mattis nunc sed blandit libero. Malesuada pellentesque elit eget gravida. Amet cursus sit amet dictum sit amet justo. Mattis rhoncus urna neque viverra justo nec. Mi quis hendrerit dolor magna eget. Tortor consequat id porta nibh venenatis. Sit amet facilisis magna etiam tempor orci.

        Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Convallis aenean et tortor at risus viverra adipiscing. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Nisi scelerisque eu ultrices vitae auctor eu augue. Consectetur a erat nam at lectus urna duis. Aliquet nibh praesent tristique magna sit amet purus gravida quis. Elit ut aliquam purus sit amet. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Nam libero justo laoreet sit. Euismod lacinia at quis risus sed vulputate. Adipiscing diam donec adipiscing tristique risus. Ornare arcu dui vivamus arcu felis bibendum ut. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Interdum velit euismod in pellentesque. Eget nunc lobortis mattis aliquam faucibus. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. At varius vel pharetra vel turpis nunc eget.

        Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Netus et malesuada fames ac turpis egestas sed tempus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Lorem dolor sed viverra ipsum nunc. Non nisi est sit amet facilisis magna etiam tempor. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Ipsum dolor sit amet consectetur adipiscing elit. Mollis aliquam ut porttitor leo. Viverra aliquet eget sit amet tellus cras adipiscing. Dolor purus non enim praesent elementum. Consectetur libero id faucibus nisl tincidunt eget. Sed turpis tincidunt id aliquet risus feugiat in ante. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Tempus urna et pharetra pharetra massa massa ultricies. Velit dignissim sodales ut eu sem integer vitae. At augue eget arcu dictum. Dui sapien eget mi proin sed libero enim sed faucibus. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Ante in nibh mauris cursus mattis.

        Egestas congue quisque egestas diam in. Eros donec ac odio tempor. Ut etiam sit amet nisl. Ut diam quam nulla porttitor massa id neque aliquam. Interdum posuere lorem ipsum dolor sit amet. Dolor magna eget est lorem ipsum. Eget velit aliquet sagittis id. Augue lacus viverra vitae congue eu consequat ac. Blandit libero volutpat sed cras. Rhoncus dolor purus non enim praesent elementum facilisis leo. Pretium aenean pharetra magna ac placerat vestibulum lectus. Elementum facilisis leo vel fringilla est ullamcorper. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Ultricies lacus sed turpis tincidunt id aliquet risus.

        Nec feugiat in fermentum posuere urna nec tincidunt praesent. Libero justo laoreet sit amet cursus sit amet. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Euismod quis viverra nibh cras. Lacus luctus accumsan tortor posuere. Enim sed faucibus turpis in eu mi. Nulla pharetra diam sit amet nisl suscipit. Fames ac turpis egestas integer eget aliquet nibh. Vitae sapien pellentesque habitant morbi tristique senectus et. Nisl tincidunt eget nullam non nisi est sit. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Adipiscing elit pellentesque habitant morbi tristique senectus et. Rhoncus dolor purus non enim. Amet mauris commodo quis imperdiet massa tincidunt nunc. Et pharetra pharetra massa massa ultricies mi quis hendrerit. Imperdiet sed euismod nisi porta lorem mollis. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Diam maecenas sed enim ut sem viverra aliquet eget sit. Risus feugiat in ante metus dictum at tempor commodo.

        Enim facilisis gravida neque convallis a cras. Ornare suspendisse sed nisi lacus sed viverra tellus in. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget arcu. Etiam non quam lacus suspendisse faucibus interdum posuere lorem. Et tortor at risus viverra adipiscing at. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Aliquet lectus proin nibh nisl condimentum. Et ultrices neque ornare aenean. Id eu nisl nunc mi. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Ultricies lacus sed turpis tincidunt id. Viverra orci sagittis eu volutpat. Dolor magna eget est lorem ipsum.

        Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Risus sed vulputate odio ut enim blandit volutpat maecenas. Est velit egestas dui id. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Euismod elementum nisi quis eleifend. Diam vel quam elementum pulvinar etiam non quam lacus. Vitae congue eu consequat ac. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Aliquam sem et tortor consequat. Amet aliquam id diam maecenas ultricies mi eget mauris. Pellentesque massa placerat duis ultricies. Nunc mattis enim ut tellus elementum sagittis. Hac habitasse platea dictumst quisque sagittis. Curabitur vitae nunc sed velit dignissim sodales ut. Leo a diam sollicitudin tempor.

        Adipiscing vitae proin sagittis nisl. At risus viverra adipiscing at in tellus. Id aliquet risus feugiat in. A cras semper auctor neque vitae tempus quam. Luctus venenatis lectus magna fringilla urna porttitor rhoncus. Sodales ut eu sem integer vitae justo eget. Aenean et tortor at risus. Quis commodo odio aenean sed adipiscing diam. Hac habitasse platea dictumst quisque sagittis purus sit. Non blandit massa enim nec dui nunc. Orci sagittis eu volutpat odio facilisis mauris. Dictum non consectetur a erat nam at. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Viverra ipsum nunc aliquet bibendum enim facilisis. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Vulputate dignissim suspendisse in est ante in nibh. Amet nisl purus in mollis nunc.

        Magna eget est lorem ipsum dolor sit amet. Sem integer vitae justo eget magna fermentum iaculis eu. Quam viverra orci sagittis eu volutpat odio facilisis. Ipsum dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Dolor purus non enim praesent elementum facilisis. Aliquam etiam erat velit scelerisque in dictum non. Cursus turpis massa tincidunt dui ut ornare. Turpis massa tincidunt dui ut ornare lectus. Velit scelerisque in dictum non consectetur a erat nam. Eu volutpat odio facilisis mauris sit amet.

        Id cursus metus aliquam eleifend mi in. Scelerisque in dictum non consectetur. Urna neque viverra justo nec ultrices dui sapien eget mi. Semper feugiat nibh sed pulvinar proin. Lorem donec massa sapien faucibus et molestie ac feugiat. Nec dui nunc mattis enim ut tellus elementum sagittis. Scelerisque fermentum dui faucibus in ornare quam. Pellentesque id nibh tortor id aliquet. Porta nibh venenatis cras sed felis eget velit. Urna neque viverra justo nec. Rutrum tellus pellentesque eu tincidunt. Semper feugiat nibh sed pulvinar proin gravida. At augue eget arcu dictum varius. Enim praesent elementum facilisis leo vel fringilla est ullamcorper eget. Amet commodo nulla facilisi nullam vehicula. Accumsan lacus vel facilisis volutpat est velit. Varius vel pharetra vel turpis nunc eget lorem dolor.

        Eget nunc lobortis mattis aliquam faucibus purus in massa. Bibendum arcu vitae elementum curabitur. Quis blandit turpis cursus in hac habitasse. Id velit ut tortor pretium. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Commodo nulla facilisi nullam vehicula ipsum a arcu. Viverra adipiscing at in tellus. Imperdiet proin fermentum leo vel orci. Eu scelerisque felis imperdiet proin. Odio morbi quis commodo odio aenean sed adipiscing. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Dolor sit amet consectetur adipiscing elit. Pretium vulputate sapien nec sagittis aliquam. Scelerisque felis imperdiet proin fermentum leo vel orci. Quis imperdiet massa tincidunt nunc.

        Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. At erat pellentesque adipiscing commodo elit at imperdiet dui. Cursus risus at ultrices mi tempus. A diam sollicitudin tempor id eu. Commodo viverra maecenas accumsan lacus vel. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Purus in massa tempor nec. Arcu dui vivamus arcu felis bibendum. Sollicitudin nibh sit amet commodo nulla facilisi nullam. Tortor vitae purus faucibus ornare suspendisse sed nisi. Pellentesque adipiscing commodo elit at imperdiet. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Sit amet consectetur adipiscing elit. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Pulvinar neque laoreet suspendisse interdum consectetur libero.

        Posuere morbi leo urna molestie at elementum eu facilisis sed. Tristique senectus et netus et malesuada fames ac. Neque aliquam vestibulum morbi blandit cursus. Etiam erat velit scelerisque in dictum non consectetur a. Ultrices gravida dictum fusce ut. Nec tincidunt praesent semper feugiat nibh. Curabitur gravida arcu ac tortor dignissim convallis aenean et. Cras pulvinar mattis nunc sed blandit libero volutpat. Eget nunc scelerisque viverra mauris in. Pharetra convallis posuere morbi leo. At quis risus sed vulputate odio ut enim. Auctor augue mauris augue neque gravida. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Lectus nulla at volutpat diam ut. Nam at lectus urna duis convallis convallis tellus id interdum. Rhoncus dolor purus non enim praesent. Eu feugiat pretium nibh ipsum consequat nisl vel pretium lectus.

        Amet purus gravida quis blandit turpis cursus in. Ornare suspendisse sed nisi lacus sed viverra tellus in. Mauris a diam maecenas sed. Eget nullam non nisi est sit amet facilisis magna. Vitae aliquet nec ullamcorper sit amet. Justo donec enim diam vulputate ut pharetra sit. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Urna duis convallis convallis tellus. Amet nulla facilisi morbi tempus iaculis urna. Nisi est sit amet facilisis magna etiam tempor orci eu. Iaculis urna id volutpat lacus. Egestas sed tempus urna et pharetra pharetra massa massa.

        Mauris ultrices eros in cursus turpis. Aliquam purus sit amet luctus venenatis lectus. Arcu odio ut sem nulla pharetra diam sit amet. Nunc eget lorem dolor sed viverra. Purus sit amet luctus venenatis lectus magna. Leo vel fringilla est ullamcorper eget nulla facilisi etiam dignissim. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Eu nisl nunc mi ipsum faucibus. Feugiat vivamus at augue eget arcu dictum varius duis at. Tristique risus nec feugiat in. Eget duis at tellus at. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Neque aliquam vestibulum morbi blandit cursus risus at. Nisl purus in mollis nunc sed id semper. Nunc eget lorem dolor sed viverra ipsum nunc aliquet.

        Leo urna molestie at elementum eu facilisis sed. Commodo elit at imperdiet dui accumsan sit amet nulla. Turpis egestas sed tempus urna et pharetra pharetra massa massa. Non sodales neque sodales ut etiam sit. Scelerisque felis imperdiet proin fermentum. In massa tempor nec feugiat nisl pretium fusce id velit. A diam sollicitudin tempor id eu nisl nunc mi ipsum. Sagittis orci a scelerisque purus semper eget duis at. Gravida neque convallis a cras. Vestibulum mattis ullamcorper velit sed ullamcorper morbi.

        Tortor at risus viverra adipiscing at in. Odio ut enim blandit volutpat. Cursus risus at ultrices mi tempus. Ut pharetra sit amet aliquam id diam. Elementum nisi quis eleifend quam. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Urna nunc id cursus metus aliquam. Tristique nulla aliquet enim tortor at auctor urna. Quis varius quam quisque id. Tortor at risus viverra adipiscing. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Nunc eget lorem dolor sed viverra ipsum nunc. Enim sed faucibus turpis in eu mi bibendum.

        Quisque id diam vel quam elementum. Amet cursus sit amet dictum sit amet justo donec enim. Aenean euismod elementum nisi quis eleifend quam. Consequat ac felis donec et odio pellentesque diam volutpat. Aliquam vestibulum morbi blandit cursus risus at ultrices mi. Eget aliquet nibh praesent tristique magna sit amet purus gravida. Magna sit amet purus gravida quis blandit. Tellus cras adipiscing enim eu turpis. Non odio euismod lacinia at quis. Ut pharetra sit amet aliquam. Turpis cursus in hac habitasse. Habitasse platea dictumst vestibulum rhoncus est. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Diam vulputate ut pharetra sit amet aliquam. Sagittis purus sit amet volutpat consequat mauris nunc. A arcu cursus vitae congue. Ut porttitor leo a diam sollicitudin tempor id eu.

        Pretium vulputate sapien nec sagittis. Viverra justo nec ultrices dui. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Posuere sollicitudin aliquam ultrices sagittis orci. Erat nam at lectus urna. Sit amet luctus venenatis lectus. Eget magna fermentum iaculis eu. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Ullamcorper malesuada proin libero nunc consequat interdum varius sit. Donec adipiscing tristique risus nec. Diam quis enim lobortis scelerisque fermentum dui faucibus in. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Integer enim neque volutpat ac.

        Enim sed faucibus turpis in eu. Pellentesque massa placerat duis ultricies. Et tortor at risus viverra adipiscing at. Id semper risus in hendrerit gravida rutrum quisque non. Elit sed vulputate mi sit amet. Sed blandit libero volutpat sed cras ornare. Mauris a diam maecenas sed enim ut. Et tortor at risus viverra adipiscing. Pellentesque habitant morbi tristique senectus et. Eu consequat ac felis donec et odio. Duis convallis convallis tellus id interdum velit laoreet. A cras semper auctor neque vitae tempus quam.

        Pharetra sit amet aliquam id diam maecenas ultricies. Enim nunc faucibus a pellentesque sit amet. Proin sed libero enim sed faucibus turpis in. Pharetra sit amet aliquam id diam. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Turpis egestas sed tempus urna et pharetra pharetra massa. Amet purus gravida quis blandit turpis cursus. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Vel facilisis volutpat est velit egestas dui. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim.

        Enim ut sem viverra aliquet eget sit amet tellus cras. Venenatis a condimentum vitae sapien pellentesque. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Est velit egestas dui id. Ac tortor dignissim convallis aenean. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Euismod elementum nisi quis eleifend quam adipiscing vitae. Vitae semper quis lectus nulla at volutpat diam ut venenatis. Euismod elementum nisi quis eleifend quam adipiscing vitae. Sapien et ligula ullamcorper malesuada proin libero. Cras ornare arcu dui vivamus arcu felis bibendum ut. At in tellus integer feugiat scelerisque varius morbi enim. Porttitor massa id neque aliquam vestibulum morbi blandit cursus risus. Dui accumsan sit amet nulla. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas.

        Elit duis tristique sollicitudin nibh sit amet. Arcu non odio euismod lacinia at quis risus sed vulputate. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. At volutpat diam ut venenatis. Nunc aliquet bibendum enim facilisis gravida neque. Lobortis feugiat vivamus at augue eget arcu dictum varius. Sed viverra tellus in hac. Odio pellentesque diam volutpat commodo. Fermentum leo vel orci porta non pulvinar neque laoreet suspendisse. Quam adipiscing vitae proin sagittis nisl rhoncus.

        Sed lectus vestibulum mattis ullamcorper velit sed. Vel eros donec ac odio tempor orci dapibus ultrices. Volutpat maecenas volutpat blandit aliquam etiam erat velit scelerisque. Mattis pellentesque id nibh tortor. Ac orci phasellus egestas tellus rutrum tellus pellentesque. Ullamcorper malesuada proin libero nunc consequat interdum varius. Fames ac turpis egestas integer eget. Egestas diam in arcu cursus euismod quis viverra nibh cras. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Vitae proin sagittis nisl rhoncus mattis rhoncus. Potenti nullam ac tortor vitae purus faucibus. Cursus sit amet dictum sit amet justo donec enim. Eu turpis egestas pretium aenean pharetra magna ac. Egestas congue quisque egestas diam in arcu cursus. Aliquam etiam erat velit scelerisque in dictum non. Aenean pharetra magna ac placerat. Ornare aenean euismod elementum nisi quis eleifend quam adipiscing vitae.

        Justo donec enim diam vulputate ut pharetra sit. Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Nunc scelerisque viverra mauris in aliquam sem. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Facilisi cras fermentum odio eu feugiat pretium nibh. Id aliquet lectus proin nibh nisl. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Eget dolor morbi non arcu. Condimentum mattis pellentesque id nibh tortor. Tincidunt id aliquet risus feugiat in ante metus dictum. Viverra nam libero justo laoreet sit amet cursus. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Pulvinar sapien et ligula ullamcorper malesuada. Eu mi bibendum neque egestas. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Congue quisque egestas diam in arcu cursus euismod quis viverra. Adipiscing at in tellus integer feugiat scelerisque. Sit amet risus nullam eget felis eget.

        Consequat semper viverra nam libero justo laoreet sit amet. Aliquam vestibulum morbi blandit cursus. Risus in hendrerit gravida rutrum quisque non tellus. Quam pellentesque nec nam aliquam sem. Pellentesque habitant morbi tristique senectus et netus et malesuada. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Gravida quis blandit turpis cursus in hac. Habitasse platea dictumst quisque sagittis purus. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Aliquam ut porttitor leo a diam sollicitudin tempor id. Molestie nunc non blandit massa enim nec. Sed risus ultricies tristique nulla aliquet enim tortor at. Faucibus vitae aliquet nec ullamcorper. Tincidunt augue interdum velit euismod in pellentesque massa. Sagittis eu volutpat odio facilisis mauris sit amet. Platea dictumst vestibulum rhoncus est pellentesque elit. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Ut diam quam nulla porttitor.

        Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Pulvinar etiam non quam lacus suspendisse faucibus interdum. Vitae et leo duis ut diam quam nulla porttitor massa. Elit pellentesque habitant morbi tristique. Turpis egestas sed tempus urna et pharetra. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Et malesuada fames ac turpis egestas integer eget. Odio tempor orci dapibus ultrices in iaculis nunc sed. Enim ut tellus elementum sagittis vitae et leo. Nibh mauris cursus mattis molestie. Congue mauris rhoncus aenean vel elit. Convallis convallis tellus id interdum velit laoreet id. Enim ut tellus elementum sagittis. Consectetur adipiscing elit duis tristique. Et pharetra pharetra massa massa ultricies mi quis. Elit at imperdiet dui accumsan sit. Facilisi nullam vehicula ipsum a arcu. Proin sagittis nisl rhoncus mattis rhoncus.

        Quam id leo in vitae turpis massa sed elementum. Vel facilisis volutpat est velit egestas dui id. Dui vivamus arcu felis bibendum ut. Eget felis eget nunc lobortis mattis aliquam faucibus. Velit ut tortor pretium viverra suspendisse. Suspendisse in est ante in nibh. Amet mauris commodo quis imperdiet massa tincidunt. Vitae tempus quam pellentesque nec nam. Sit amet est placerat in egestas erat imperdiet sed euismod. Nunc vel risus commodo viverra maecenas accumsan lacus. Vestibulum lectus mauris ultrices eros. Morbi tincidunt augue interdum velit euismod in. Facilisis leo vel fringilla est. Facilisi etiam dignissim diam quis enim. Turpis tincidunt id aliquet risus. Et tortor consequat id porta nibh venenatis.

        Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Nisi porta lorem mollis aliquam ut porttitor leo a. Consectetur a erat nam at lectus urna duis convallis. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Morbi tincidunt ornare massa eget egestas purus viverra. Lacus viverra vitae congue eu. Dui accumsan sit amet nulla facilisi morbi. At consectetur lorem donec massa sapien faucibus et. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Turpis nunc eget lorem dolor sed. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Diam maecenas sed enim ut sem. Mauris a diam maecenas sed enim ut. Amet massa vitae tortor condimentum lacinia. Nunc id cursus metus aliquam eleifend mi. Massa ultricies mi quis hendrerit dolor. Odio pellentesque diam volutpat commodo sed. Nascetur ridiculus mus mauris vitae ultricies. Donec massa sapien faucibus et molestie ac feugiat sed.

        Vulputate enim nulla aliquet porttitor lacus luctus. Varius duis at consectetur lorem donec. Non arcu risus quis varius quam quisque id diam. Imperdiet sed euismod nisi porta lorem. Ut aliquam purus sit amet luctus. Tempus iaculis urna id volutpat. At varius vel pharetra vel. Elit pellentesque habitant morbi tristique. Non diam phasellus vestibulum lorem sed risus ultricies. Lorem ipsum dolor sit amet consectetur adipiscing elit. Sed faucibus turpis in eu mi bibendum neque. Mus mauris vitae ultricies leo integer malesuada nunc vel. Elit ut aliquam purus sit amet luctus venenatis. Leo a diam sollicitudin tempor id. Sit amet risus nullam eget felis eget nunc. Amet commodo nulla facilisi nullam vehicula ipsum. Hendrerit dolor magna eget est lorem ipsum dolor sit amet.

        Pellentesque habitant morbi tristique senectus et netus et malesuada. Cursus risus at ultrices mi tempus imperdiet nulla. Arcu dui vivamus arcu felis bibendum. Nunc sed augue lacus viverra vitae. Cursus eget nunc scelerisque viverra. Auctor elit sed vulputate mi sit amet mauris commodo quis. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Suspendisse sed nisi lacus sed viverra tellus. Commodo ullamcorper a lacus vestibulum sed. Sit amet volutpat consequat mauris nunc. Sit amet nulla facilisi morbi. Auctor urna nunc id cursus metus aliquam eleifend mi. Diam vulputate ut pharetra sit. Sed id semper risus in hendrerit gravida rutrum. Arcu non odio euismod lacinia at quis risus. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Ultrices gravida dictum fusce ut placerat. Non sodales neque sodales ut etiam sit amet nisl.

        Leo in vitae turpis massa sed elementum tempus. A condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Dolor sit amet consectetur adipiscing elit ut aliquam. Quam viverra orci sagittis eu volutpat. Mattis pellentesque id nibh tortor id aliquet lectus proin. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Et malesuada fames ac turpis egestas integer eget aliquet. In mollis nunc sed id semper risus in hendrerit. Nibh nisl condimentum id venenatis a condimentum. Amet risus nullam eget felis eget nunc. Diam volutpat commodo sed egestas egestas fringilla phasellus. Lorem ipsum dolor sit amet. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Velit aliquet sagittis id consectetur purus ut. Elementum curabitur vitae nunc sed. Enim ut tellus elementum sagittis vitae. Enim nec dui nunc mattis. Sagittis purus sit amet volutpat consequat mauris.

        Cras tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Suscipit tellus mauris a diam maecenas. Vitae proin sagittis nisl rhoncus. Eu non diam phasellus vestibulum lorem sed. Mauris pellentesque pulvinar pellentesque habitant morbi. Turpis egestas sed tempus urna et pharetra pharetra massa. Eros donec ac odio tempor orci. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Lorem dolor sed viverra ipsum. Tristique senectus et netus et malesuada fames.

        Eget mauris pharetra et ultrices neque ornare aenean. Id neque aliquam vestibulum morbi blandit cursus risus. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Suspendisse sed nisi lacus sed viverra tellus in. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Nisl nisi scelerisque eu ultrices vitae. Facilisi nullam vehicula ipsum a arcu cursus vitae congue mauris. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Vitae nunc sed velit dignissim sodales ut. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Purus sit amet volutpat consequat mauris nunc. Sed viverra ipsum nunc aliquet bibendum. Commodo elit at imperdiet dui accumsan sit amet nulla facilisi. Feugiat sed lectus vestibulum mattis. Purus ut faucibus pulvinar elementum integer. Id diam vel quam elementum pulvinar etiam non quam. Quam elementum pulvinar etiam non. Arcu risus quis varius quam quisque id diam vel quam.

        Blandit libero volutpat sed cras ornare arcu dui vivamus. Morbi enim nunc faucibus a. Id nibh tortor id aliquet lectus proin nibh. Tortor consequat id porta nibh. Posuere lorem ipsum dolor sit amet consectetur. Commodo sed egestas egestas fringilla. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Gravida cum sociis natoque penatibus. Facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Posuere morbi leo urna molestie. Purus in massa tempor nec. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Nulla at volutpat diam ut venenatis tellus in metus. Tortor condimentum lacinia quis vel eros. Arcu ac tortor dignissim convallis aenean et tortor. Facilisi etiam dignissim diam quis enim lobortis.

        Odio tempor orci dapibus ultrices in iaculis nunc. At risus viverra adipiscing at in tellus integer feugiat. Suspendisse sed nisi lacus sed viverra. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Pretium nibh ipsum consequat nisl vel pretium. Dui ut ornare lectus sit amet est placerat in egestas. Velit dignissim sodales ut eu sem integer vitae justo. A pellentesque sit amet porttitor eget dolor. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Hac habitasse platea dictumst vestibulum. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Ullamcorper velit sed ullamcorper morbi tincidunt. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Lacus suspendisse faucibus interdum posuere lorem. Fermentum odio eu feugiat pretium nibh. Et netus et malesuada fames ac turpis egestas integer. Elit at imperdiet dui accumsan sit amet nulla. Dignissim enim sit amet venenatis urna cursus eget nunc.

        Nulla aliquet enim tortor at auctor urna. Orci dapibus ultrices in iaculis nunc. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Sollicitudin ac orci phasellus egestas tellus. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Id diam maecenas ultricies mi eget mauris pharetra et. Fringilla phasellus faucibus scelerisque eleifend donec. Vitae justo eget magna fermentum iaculis eu non diam. Euismod in pellentesque massa placerat duis ultricies lacus. Id aliquet lectus proin nibh nisl. Aliquet porttitor lacus luctus accumsan tortor posuere ac.

        Purus in mollis nunc sed id semper risus. Tortor pretium viverra suspendisse potenti nullam ac tortor. Ut aliquam purus sit amet luctus venenatis. Vitae turpis massa sed elementum tempus egestas sed. Sagittis vitae et leo duis ut diam quam. Vestibulum sed arcu non odio euismod lacinia at quis. Dictum at tempor commodo ullamcorper a. Vitae aliquet nec ullamcorper sit amet. Sed libero enim sed faucibus turpis in eu mi bibendum. Ut tellus elementum sagittis vitae et leo duis. Aliquet lectus proin nibh nisl condimentum id venenatis. Nibh sed pulvinar proin gravida. Gravida rutrum quisque non tellus orci ac auctor augue mauris.

        Malesuada fames ac turpis egestas. Adipiscing bibendum est ultricies integer quis auctor elit. Placerat vestibulum lectus mauris ultrices eros in. Est ultricies integer quis auctor elit sed vulputate mi. Ut pharetra sit amet aliquam id diam. Elementum nisi quis eleifend quam. Ut aliquam purus sit amet luctus venenatis. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Est sit amet facilisis magna etiam tempor orci eu. Sit amet tellus cras adipiscing enim. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Amet facilisis magna etiam tempor orci eu. Sed id semper risus in hendrerit gravida. Viverra accumsan in nisl nisi. Semper viverra nam libero justo laoreet sit amet cursus sit.

        Eget dolor morbi non arcu risus quis varius quam. Feugiat in ante metus dictum at tempor. Aliquet lectus proin nibh nisl condimentum id venenatis a. Morbi enim nunc faucibus a pellentesque sit amet. Ultrices eros in cursus turpis massa. Aenean et tortor at risus. Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Sem fringilla ut morbi tincidunt augue interdum. Enim nec dui nunc mattis enim. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Euismod elementum nisi quis eleifend quam adipiscing. At varius vel pharetra vel turpis nunc eget lorem. Pharetra diam sit amet nisl suscipit. Sem integer vitae justo eget magna fermentum iaculis eu. Aenean euismod elementum nisi quis eleifend quam adipiscing. Tempor nec feugiat nisl pretium fusce id velit ut tortor. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Montes nascetur ridiculus mus mauris vitae ultricies leo integer.

        Libero nunc consequat interdum varius sit amet mattis vulputate. Nisl vel pretium lectus quam id leo in vitae turpis. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Et ultrices neque ornare aenean euismod elementum nisi. Euismod elementum nisi quis eleifend. Egestas maecenas pharetra convallis posuere morbi. Ac auctor augue mauris augue neque gravida in fermentum et. Dolor magna eget est lorem ipsum dolor sit. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Morbi leo urna molestie at elementum eu facilisis. Sit amet nisl suscipit adipiscing bibendum est. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Posuere lorem ipsum dolor sit. Enim praesent elementum facilisis leo. Elementum pulvinar etiam non quam lacus. Id diam maecenas ultricies mi eget mauris pharetra.

        Mauris cursus mattis molestie a iaculis. Viverra adipiscing at in tellus. Dui vivamus arcu felis bibendum ut tristique et. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim facilisis. Ac placerat vestibulum lectus mauris ultrices eros. In arcu cursus euismod quis viverra nibh cras pulvinar. Sit amet est placerat in egestas erat imperdiet sed euismod. Dui faucibus in ornare quam viverra. Pellentesque massa placerat duis ultricies. Sed vulputate odio ut enim. Sed euismod nisi porta lorem mollis. Feugiat vivamus at augue eget arcu dictum varius duis at. Ornare massa eget egestas purus viverra accumsan in. Aliquet eget sit amet tellus cras. Adipiscing elit ut aliquam purus sit amet luctus venenatis lectus. A arcu cursus vitae congue mauris rhoncus. A scelerisque purus semper eget duis. Consequat ac felis donec et odio pellentesque. Lorem donec massa sapien faucibus et. At tempor commodo ullamcorper a lacus vestibulum sed arcu non.
        """
        
        self.measure {
            let view = MockCounterView()
            let networkService = MockNetworkService(text: SandboxText(success: true, data: "hello", errors: nil))
            presenter = CounterPresenter(view: view, networkService: networkService, router: router)
            presenter.countCharacters(inputText: testText)
        }
    }

}
